name: deploy-docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          # submodules: true

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 22
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: build docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
